//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classify
    {
        public Classify()
        {
            this.Classify1 = new HashSet<Classify>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Image { get; set; }
        public bool Show { get; set; }
        public int CreateUserID { get; set; }
        public int IsDelete { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Classify> Classify1 { get; set; }
        public virtual Classify Classify2 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
