//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_DataDictionary
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public int TableKind { get; set; }
        public string AttrName { get; set; }
        public string Alias { get; set; }
        public Nullable<System.DateTime> DT_CREATEDATE { get; set; }
        public Nullable<int> ST_CREATEUSER { get; set; }
        public Nullable<System.DateTime> DT_MODIFYDATE { get; set; }
        public Nullable<int> ST_MODIFYUSER { get; set; }
        public string IPAdress { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> DataFlag { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Province { get; set; }
        public string City { get; set; }
        public string StreetAddress { get; set; }
        public string DepartmentNumber { get; set; }
        public string ZipCode { get; set; }
        public string CompanyName { get; set; }
        public string SeasonZhName { get; set; }
        public string SelectCustomer { get; set; }
    }
}
