//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_temp
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public string C_CallPeople { get; set; }
        public string C_Telephone { get; set; }
        public string C_Cellphone { get; set; }
        public string C_Fax { get; set; }
        public string C_Adress { get; set; }
        public string C_EmailAdress { get; set; }
    }
}
