//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_ShipmentOrderCabinet
    {
        public Delivery_ShipmentOrderCabinet()
        {
            this.Delivery_ShipmentOrderProduct = new HashSet<Delivery_ShipmentOrderProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ShipmentOrderID { get; set; }
        public Nullable<int> Shipment_CabinetID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> SumVolume { get; set; }
        public Nullable<decimal> SumWeightGross { get; set; }
        public Nullable<decimal> SumWeightNet { get; set; }
        public Nullable<System.DateTime> GatherDate { get; set; }
        public string GatherAddress { get; set; }
        public Nullable<int> GatherType { get; set; }
        public string GatherDescription { get; set; }
        public bool IsSendEmailToFactory { get; set; }
        public Nullable<decimal> RegisterFees { get; set; }
        public Nullable<decimal> CabinetVolume { get; set; }
        public Nullable<decimal> CabinetRemainderVolume { get; set; }
        public Nullable<int> ShipToPortID { get; set; }
        public int CabinetIndex { get; set; }
        public Nullable<System.DateTime> GatherEndDate { get; set; }
        public Nullable<System.DateTime> ShippingDateStart { get; set; }
        public Nullable<System.DateTime> ShippingDateEnd { get; set; }
        public Nullable<int> CabinetType { get; set; }
        public string CabinetNumber { get; set; }
        public string SealingNumber { get; set; }
        public string OceanVessel { get; set; }
    
        public virtual Delivery_ShipmentOrder Delivery_ShipmentOrder { get; set; }
        public virtual Shipment_Cabinet Shipment_Cabinet { get; set; }
        public virtual ICollection<Delivery_ShipmentOrderProduct> Delivery_ShipmentOrderProduct { get; set; }
    }
}
