//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_ShipmentOrder
    {
        public Delivery_ShipmentOrder()
        {
            this.Delivery_ShipmentNotificationHistory = new HashSet<Delivery_ShipmentNotificationHistory>();
            this.Delivery_ShipmentOrderCabinet = new HashSet<Delivery_ShipmentOrderCabinet>();
            this.Delivery_ShipmentOrderHistory = new HashSet<Delivery_ShipmentOrderHistory>();
            this.Delivery_ShipmentRegisterFeesHistory = new HashSet<Delivery_ShipmentRegisterFeesHistory>();
            this.DocumentsIndexings = new HashSet<DocumentsIndexing>();
            this.Inspection_InspectionClearance = new HashSet<Inspection_InspectionClearance>();
            this.Inspection_InspectionCustoms = new HashSet<Inspection_InspectionCustoms>();
            this.Inspection_InspectionExchange = new HashSet<Inspection_InspectionExchange>();
        }
    
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int StatusID { get; set; }
        public string CheckSuggest { get; set; }
        public Nullable<int> Shipment_AgencyID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public int NotificationStatusID { get; set; }
        public int RegisterFeesStatusID { get; set; }
        public string NotificationCheckSuggest { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public Nullable<int> ApproverIndexNotification { get; set; }
        public Nullable<int> PortID { get; set; }
        public string OrderIDList { get; set; }
        public bool IsMerge { get; set; }
        public Nullable<int> ST_CREATEUSERNotification { get; set; }
        public Nullable<System.DateTime> Notification_DT_MODIFYDATE { get; set; }
        public Nullable<System.DateTime> RegisterFees_DT_MODIFYDATE { get; set; }
        public Nullable<int> Notification_ST_MODIFYUSER { get; set; }
        public Nullable<int> RegisterFees_ST_MODIFYUSER { get; set; }
        public bool IsBatchShipped { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Delivery_ShipmentNotificationHistory> Delivery_ShipmentNotificationHistory { get; set; }
        public virtual Order Order { get; set; }
        public virtual Shipment_Agencies Shipment_Agencies { get; set; }
        public virtual ICollection<Delivery_ShipmentOrderCabinet> Delivery_ShipmentOrderCabinet { get; set; }
        public virtual ICollection<Delivery_ShipmentOrderHistory> Delivery_ShipmentOrderHistory { get; set; }
        public virtual ICollection<Delivery_ShipmentRegisterFeesHistory> Delivery_ShipmentRegisterFeesHistory { get; set; }
        public virtual ICollection<DocumentsIndexing> DocumentsIndexings { get; set; }
        public virtual ICollection<Inspection_InspectionClearance> Inspection_InspectionClearance { get; set; }
        public virtual ICollection<Inspection_InspectionCustoms> Inspection_InspectionCustoms { get; set; }
        public virtual ICollection<Inspection_InspectionExchange> Inspection_InspectionExchange { get; set; }
    }
}
