//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_EncasementsProducts
    {
        public int EncasementsProductID { get; set; }
        public int EncasementsID { get; set; }
        public int OrderProductID { get; set; }
        public Nullable<decimal> OuterLength { get; set; }
        public Nullable<decimal> OuterWidth { get; set; }
        public Nullable<decimal> OuterHeight { get; set; }
        public Nullable<decimal> WeightGross { get; set; }
        public Nullable<decimal> WeightNet { get; set; }
        public bool IsProductMixed { get; set; }
        public Nullable<int> ParentProductMixedID { get; set; }
    
        public virtual Delivery_Encasements Delivery_Encasements { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
