//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Encasements
    {
        public Delivery_Encasements()
        {
            this.Delivery_EncasementsHis = new HashSet<Delivery_EncasementsHis>();
            this.Delivery_EncasementsProducts = new HashSet<Delivery_EncasementsProducts>();
        }
    
        public int EncasementsID { get; set; }
        public int ContractsID { get; set; }
        public int EncasementsStatus { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public string CreateTerminal { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateTerminal { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Delivery_EncasementsHis> Delivery_EncasementsHis { get; set; }
        public virtual ICollection<Delivery_EncasementsProducts> Delivery_EncasementsProducts { get; set; }
        public virtual Purchase_Contract Purchase_Contract { get; set; }
    }
}
