//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsIndexing
    {
        public DocumentsIndexing()
        {
            this.DocumentsIndexingHistories = new HashSet<DocumentsIndexingHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomsUnit { get; set; }
        public bool GuaranteeShipments { get; set; }
        public bool IsOther { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public int OrderID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> Managers_UserID { get; set; }
        public Nullable<System.DateTime> Managers_Date { get; set; }
        public Nullable<int> ShipmentOrderID { get; set; }
        public Nullable<System.DateTime> DocumentsIndexingUploadDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public int DocumentsIndexingType { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Delivery_ShipmentOrder Delivery_ShipmentOrder { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<DocumentsIndexingHistory> DocumentsIndexingHistories { get; set; }
    }
}
