//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public Factory()
        {
            this.Purchase_Contract = new HashSet<Purchase_Contract>();
            this.Purchase_OutContracts = new HashSet<Purchase_OutContracts>();
            this.Quot_QuotProduct = new HashSet<Quot_QuotProduct>();
            this.Quot_QuotProductHistory = new HashSet<Quot_QuotProductHistory>();
            this.Sale_SendSamples = new HashSet<Sale_SendSamples>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.Products = new HashSet<Product>();
            this.ProductFittings = new HashSet<ProductFitting>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public string City { get; set; }
        public string CallPeople { get; set; }
        public string Telephone { get; set; }
        public string Cellphone { get; set; }
        public string Fax { get; set; }
        public string F_Address { get; set; }
        public string EmailAdress { get; set; }
        public string Abbreviation { get; set; }
        public string Duty { get; set; }
        public string Province { get; set; }
        public string CityArea { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> DT_CREATEDATE { get; set; }
        public string AllAdress { get; set; }
        public Nullable<int> ST_CREATEUSER { get; set; }
        public Nullable<System.DateTime> DT_MODIFYDATE { get; set; }
        public Nullable<int> ST_MODIFYUSER { get; set; }
        public string IPAdress { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public int DataFlag { get; set; }
        public Nullable<int> Hierarchy { get; set; }
        public Nullable<decimal> RegisterFees { get; set; }
        public string EnglishName { get; set; }
        public string EnglishAddress { get; set; }
        public Nullable<int> CurrencyType { get; set; }
    
        public virtual Hierarchy Hierarchy1 { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Purchase_Contract> Purchase_Contract { get; set; }
        public virtual ICollection<Purchase_OutContracts> Purchase_OutContracts { get; set; }
        public virtual ICollection<Quot_QuotProduct> Quot_QuotProduct { get; set; }
        public virtual ICollection<Quot_QuotProductHistory> Quot_QuotProductHistory { get; set; }
        public virtual ICollection<Sale_SendSamples> Sale_SendSamples { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductFitting> ProductFittings { get; set; }
    }
}
