//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceProduct
    {
        public int ID { get; set; }
        public int OrderProductID { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> FactoryDate { get; set; }
        public Nullable<decimal> InvoicedAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> CertifiedInvoiceDate { get; set; }
        public Nullable<decimal> USDExchangeRate { get; set; }
        public Nullable<System.DateTime> ClearanceDate { get; set; }
        public Nullable<decimal> ClearanceAmount { get; set; }
        public Nullable<decimal> BankFees { get; set; }
        public string CustomsNumber { get; set; }
        public Nullable<bool> PreRecordedStatus { get; set; }
        public Nullable<decimal> OtherExpensesDeduction { get; set; }
        public Nullable<decimal> FactoryFees { get; set; }
        public Nullable<decimal> PacksDetectFees { get; set; }
        public Nullable<decimal> PortCharges { get; set; }
        public Nullable<decimal> InternationalCourierFees { get; set; }
        public Nullable<decimal> OtherFees { get; set; }
        public Nullable<decimal> CompanyManagementRate { get; set; }
        public Nullable<decimal> RefundRate { get; set; }
        public string Comment { get; set; }
        public int ModuleType { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
