//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_InspectionCustomsDetail
    {
        public Inspection_InspectionCustomsDetail()
        {
            this.Inspection_InspectionCustomsProduct = new HashSet<Inspection_InspectionCustomsProduct>();
        }
    
        public int ID { get; set; }
        public int InspectionCustomsID { get; set; }
        public string InvoiceNO { get; set; }
        public string SalesContractNO { get; set; }
        public int TransportType { get; set; }
        public int ExchangeType { get; set; }
        public string SourceAreaWithin { get; set; }
        public string TransactionType { get; set; }
        public string SaleContractContent { get; set; }
        public string TeamOfThePayment { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> TradeType { get; set; }
    
        public virtual Inspection_InspectionCustoms Inspection_InspectionCustoms { get; set; }
        public virtual ICollection<Inspection_InspectionCustomsProduct> Inspection_InspectionCustomsProduct { get; set; }
    }
}
