//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_InspectionReceiptList
    {
        public Inspection_InspectionReceiptList()
        {
            this.Inspection_InspectionReceipt = new HashSet<Inspection_InspectionReceipt>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ShipmentOrderID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> HSCode { get; set; }
        public Nullable<int> PurchaseContractID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public Nullable<bool> IsNeedInspection { get; set; }
        public bool IsShowNeedInspection { get; set; }
        public Nullable<int> ReceiptIndex { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Inspection_InspectionReceipt> Inspection_InspectionReceipt { get; set; }
        public virtual Purchase_Contract Purchase_Contract { get; set; }
    }
}
