//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_InspectionReceiptHis
    {
        public int INHISID { get; set; }
        public int InspectionReceiptID { get; set; }
        public int AuditUserID { get; set; }
        public string AuditIdea { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int InspectionReceiptStatus { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Inspection_InspectionReceipt Inspection_InspectionReceipt { get; set; }
    }
}
