//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_InspectionCustomsProduct
    {
        public Inspection_InspectionCustomsProduct()
        {
            this.Inspection_InspectionCustomsProduct2 = new HashSet<Inspection_InspectionCustomsProduct2>();
        }
    
        public int ID { get; set; }
        public int InspectionCustomsDetailID { get; set; }
        public Nullable<int> HSID { get; set; }
        public decimal ICUnitPrice { get; set; }
        public string ICUnitRetail { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Qty { get; set; }
        public string HSCodeName { get; set; }
        public Nullable<int> SelectBoxQty { get; set; }
        public string HSCodeEngName { get; set; }
    
        public virtual Inspection_InspectionCustomsDetail Inspection_InspectionCustomsDetail { get; set; }
        public virtual ICollection<Inspection_InspectionCustomsProduct2> Inspection_InspectionCustomsProduct2 { get; set; }
    }
}
