//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_InspectionExchange
    {
        public Inspection_InspectionExchange()
        {
            this.Inspection_InspectionExchangeHis = new HashSet<Inspection_InspectionExchangeHis>();
        }
    
        public int InspectionExchangeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public int ShipmentOrderID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> LargestSettlementDate { get; set; }
        public string CreditNumber { get; set; }
        public Nullable<System.DateTime> ShipDateStart { get; set; }
        public Nullable<System.DateTime> ShipDateEnd { get; set; }
        public Nullable<int> PortOfEntry { get; set; }
        public Nullable<decimal> MiscPercent { get; set; }
        public string BoxNumber { get; set; }
        public string SealNumber { get; set; }
        public string InvoiceOF { get; set; }
        public Nullable<int> TransshipmentPortID { get; set; }
        public Nullable<System.DateTime> ActualShippingDate { get; set; }
        public string FactoryIDList { get; set; }
        public Nullable<int> TradeType { get; set; }
        public Nullable<int> ShipTo { get; set; }
        public bool IsTest { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Delivery_ShipmentOrder Delivery_ShipmentOrder { get; set; }
        public virtual Orders_AcceptInformation Orders_AcceptInformation { get; set; }
        public virtual ICollection<Inspection_InspectionExchangeHis> Inspection_InspectionExchangeHis { get; set; }
    }
}
