//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_AcceptInformation
    {
        public Orders_AcceptInformation()
        {
            this.Inspection_InspectionClearance = new HashSet<Inspection_InspectionClearance>();
            this.Inspection_InspectionExchange = new HashSet<Inspection_InspectionExchange>();
            this.Sale_SendSamples = new HashSet<Sale_SendSamples>();
        }
    
        public int AIID { get; set; }
        public int OCID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string CompanyName { get; set; }
        public string MobilePhone { get; set; }
        public string TelPhone { get; set; }
        public Nullable<short> AddressType { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public int Region { get; set; }
        public int Province { get; set; }
        public int Country { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDefault { get; set; }
        public bool IsDelete { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Inspection_InspectionClearance> Inspection_InspectionClearance { get; set; }
        public virtual ICollection<Inspection_InspectionExchange> Inspection_InspectionExchange { get; set; }
        public virtual Orders_Customers Orders_Customers { get; set; }
        public virtual ICollection<Sale_SendSamples> Sale_SendSamples { get; set; }
    }
}
