//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Contacts
    {
        public int OLID { get; set; }
        public int OCID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Duty { get; set; }
        public string MobilePhone { get; set; }
        public string TelPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public string SeasonIDList { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Orders_Customers Orders_Customers { get; set; }
    }
}
