//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_ProducePlanHistory
    {
        public int ID { get; set; }
        public int ProduceID { get; set; }
        public string HistoryProducePeople { get; set; }
        public Nullable<int> HistoryProduceResult { get; set; }
        public string HistorySomeThing { get; set; }
        public Nullable<System.DateTime> HistoryProduceDate { get; set; }
    
        public virtual Plan_ProducePlan Plan_ProducePlan { get; set; }
    }
}
