//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_ProducePlan
    {
        public Plan_ProducePlan()
        {
            this.Plan_ProducePlanHistory = new HashSet<Plan_ProducePlanHistory>();
        }
    
        public int ID { get; set; }
        public int PurchaseID { get; set; }
        public int Status { get; set; }
        public Nullable<int> Result { get; set; }
        public string SomeThing { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public Nullable<System.DateTime> DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAdress { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string OrderList { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public Nullable<int> ST_CREATEUSER2 { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Purchase_Contract Purchase_Contract { get; set; }
        public virtual ICollection<Plan_ProducePlanHistory> Plan_ProducePlanHistory { get; set; }
    }
}
