//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFitting
    {
        public int ID { get; set; }
        public int FactoryID { get; set; }
        public string No { get; set; }
        public string Image { get; set; }
        public decimal Length { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal PriceFactory { get; set; }
        public int CurrencyType { get; set; }
        public string Comment { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public Nullable<System.DateTime> DT_MODIFYDATE { get; set; }
        public Nullable<int> ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Qty { get; set; }
        public int ModuleType { get; set; }
        public string Name { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> RootID { get; set; }
        public Nullable<decimal> FeesRate { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual Product Product { get; set; }
    }
}
