//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSample
    {
        public int PSID { get; set; }
        public Nullable<decimal> SSID { get; set; }
        public Nullable<decimal> PDID { get; set; }
        public Nullable<int> IsMod { get; set; }
        public string NoteA { get; set; }
        public string NoteB { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
