//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_ContractBatch
    {
        public Purchase_ContractBatch()
        {
            this.Purchase_ContractProduct = new HashSet<Purchase_ContractProduct>();
        }
    
        public int ID { get; set; }
        public int Times { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int PurchaseContractID { get; set; }
        public decimal BatchAmount { get; set; }
    
        public virtual Purchase_Contract Purchase_Contract { get; set; }
        public virtual ICollection<Purchase_ContractProduct> Purchase_ContractProduct { get; set; }
    }
}
