//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_ThirdPartyVerification
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string Comment { get; set; }
        public int StatusID { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> InspectionVerificationFee { get; set; }
        public Nullable<decimal> InspectionVerificationFee_ForFactory { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Order Order { get; set; }
    }
}
