//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_OutContractProduct
    {
        public int ID { get; set; }
        public int OrderProductID { get; set; }
        public int OCPacksID { get; set; }
        public string TagDescribe { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Purchase_OutContractsPacks Purchase_OutContractsPacks { get; set; }
    }
}
