//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Contract
    {
        public Purchase_Contract()
        {
            this.Delivery_Encasements = new HashSet<Delivery_Encasements>();
            this.Inspection_InspectionReceiptList = new HashSet<Inspection_InspectionReceiptList>();
            this.Plan_ProducePlan = new HashSet<Plan_ProducePlan>();
            this.ThirdParty_Inspection = new HashSet<ThirdParty_Inspection>();
            this.Purchase_PacksHis = new HashSet<Purchase_PacksHis>();
            this.Purchase_ContractBatch = new HashSet<Purchase_ContractBatch>();
            this.Purchase_ContractHistory = new HashSet<Purchase_ContractHistory>();
            this.Purchase_OutContracts = new HashSet<Purchase_OutContracts>();
            this.Purchase_PackProductsUPC = new HashSet<Purchase_PackProductsUPC>();
            this.Purchase_Packs = new HashSet<Purchase_Packs>();
            this.Purchase_ShippingMarkHistory = new HashSet<Purchase_ShippingMarkHistory>();
            this.Purchase_ThreeTimesQC = new HashSet<Purchase_ThreeTimesQC>();
        }
    
        public int ID { get; set; }
        public string PurchaseNumber { get; set; }
        public int FactoryID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int AfterDate { get; set; }
        public decimal AllAmount { get; set; }
        public int PortID { get; set; }
        public bool IsImmediatelySend { get; set; }
        public bool IsThirdVerification { get; set; }
        public bool IsThirdAudits { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public string Comment { get; set; }
        public int PurchaseStatus { get; set; }
        public int PacksStatus { get; set; }
        public Nullable<bool> IsOutsourcing { get; set; }
        public string AuditPacksIdea { get; set; }
        public string ContractTerms { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int EncasementStatus { get; set; }
        public string AuditEncasementIdea { get; set; }
        public Nullable<System.DateTime> EncasementUpdateDate { get; set; }
        public Nullable<System.DateTime> PacksUpdateDate { get; set; }
        public bool IsThirdTest { get; set; }
        public Nullable<int> ApproverIndexPurchaseContract { get; set; }
        public Nullable<int> ApproverIndexPacks { get; set; }
        public Nullable<int> ApproverIndexEncasement { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Port { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> AllQty { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public int ShippingMark_StatusID { get; set; }
        public string ShippingMark_Comment { get; set; }
        public Nullable<int> ShippingMark_CustomerID { get; set; }
        public Nullable<int> ShippingMark_CreateUser { get; set; }
        public Nullable<System.DateTime> ShippingMark_ModifyDate { get; set; }
        public Nullable<int> ApproverIndexShippingMark { get; set; }
        public bool IsThirdSampling { get; set; }
        public Nullable<decimal> DocumentsIndexing_OtherFees { get; set; }
        public Nullable<bool> DocumentsIndexing_IsGuaranteeShipments { get; set; }
        public Nullable<int> ShippingMark_AcceptInformationID { get; set; }
        public int ContractType { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual ICollection<Delivery_Encasements> Delivery_Encasements { get; set; }
        public virtual ICollection<Inspection_InspectionReceiptList> Inspection_InspectionReceiptList { get; set; }
        public virtual Orders_Customers Orders_Customers { get; set; }
        public virtual ICollection<Plan_ProducePlan> Plan_ProducePlan { get; set; }
        public virtual ICollection<ThirdParty_Inspection> ThirdParty_Inspection { get; set; }
        public virtual ICollection<Purchase_PacksHis> Purchase_PacksHis { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual ICollection<Purchase_ContractBatch> Purchase_ContractBatch { get; set; }
        public virtual ICollection<Purchase_ContractHistory> Purchase_ContractHistory { get; set; }
        public virtual ICollection<Purchase_OutContracts> Purchase_OutContracts { get; set; }
        public virtual ICollection<Purchase_PackProductsUPC> Purchase_PackProductsUPC { get; set; }
        public virtual ICollection<Purchase_Packs> Purchase_Packs { get; set; }
        public virtual ICollection<Purchase_ShippingMarkHistory> Purchase_ShippingMarkHistory { get; set; }
        public virtual ICollection<Purchase_ThreeTimesQC> Purchase_ThreeTimesQC { get; set; }
    }
}
