//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_ThreeTimesQC
    {
        public Purchase_ThreeTimesQC()
        {
            this.Purchase_ThreeTimesQCHistory = new HashSet<Purchase_ThreeTimesQCHistory>();
        }
    
        public int ID { get; set; }
        public int PurchaseContractID { get; set; }
        public string Comment { get; set; }
        public int StatusID { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> RecoveryUserID { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public Nullable<int> RecoveryStatusID { get; set; }
        public Nullable<System.DateTime> RecoveryModifyDate { get; set; }
        public Nullable<int> RecoveryModifyUser { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public string RecoveryAddress { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> ST_CREATEUSER2 { get; set; }
        public string Suggest { get; set; }
        public int ApprovalStatus { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Purchase_Contract Purchase_Contract { get; set; }
        public virtual ICollection<Purchase_ThreeTimesQCHistory> Purchase_ThreeTimesQCHistory { get; set; }
    }
}
