//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_OutContracts
    {
        public Purchase_OutContracts()
        {
            this.Purchase_OutContractHis = new HashSet<Purchase_OutContractHis>();
            this.Purchase_OutContractsPacks = new HashSet<Purchase_OutContractsPacks>();
        }
    
        public int ID { get; set; }
        public int ContractsID { get; set; }
        public int FactoryID { get; set; }
        public int DeliveryID { get; set; }
        public string OutContracNo { get; set; }
        public Nullable<decimal> OutContractSum { get; set; }
        public string Clasue { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DeliveryDateStart { get; set; }
        public Nullable<System.DateTime> DeliveryDateEnd { get; set; }
        public Nullable<int> OutContractStatus { get; set; }
        public string AuditIdea { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public string CreateTerminal { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateTerminal { get; set; }
        public string DeliveryName { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public decimal OthersFee { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Purchase_Contract Purchase_Contract { get; set; }
        public virtual ICollection<Purchase_OutContractHis> Purchase_OutContractHis { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual ICollection<Purchase_OutContractsPacks> Purchase_OutContractsPacks { get; set; }
    }
}
