//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_OutContractsPacks
    {
        public Purchase_OutContractsPacks()
        {
            this.Purchase_OutContractProduct = new HashSet<Purchase_OutContractProduct>();
        }
    
        public int ID { get; set; }
        public int OutContractsID { get; set; }
        public int PacksID { get; set; }
        public string PacksRemark { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<Purchase_OutContractProduct> Purchase_OutContractProduct { get; set; }
        public virtual Purchase_OutContracts Purchase_OutContracts { get; set; }
        public virtual Purchase_Packs Purchase_Packs { get; set; }
    }
}
