//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_ContractProduct
    {
        public int ID { get; set; }
        public int OrderProductID { get; set; }
        public int PurchaseContractBatchID { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public string Comment { get; set; }
        public string MixedMode { get; set; }
        public string OtherComment { get; set; }
        public string PackageName { get; set; }
        public Nullable<bool> IsFragile { get; set; }
        public Nullable<int> CarbinetType { get; set; }
        public bool IsProductMixed { get; set; }
        public Nullable<int> ParentProductMixedID { get; set; }
    
        public virtual Purchase_ContractBatch Purchase_ContractBatch { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
