//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Packs
    {
        public Purchase_Packs()
        {
            this.Purchase_OutContractsPacks = new HashSet<Purchase_OutContractsPacks>();
            this.Purchase_PackProducts = new HashSet<Purchase_PackProducts>();
        }
    
        public int ID { get; set; }
        public int ContractsID { get; set; }
        public int TagID { get; set; }
        public string TagDescribe { get; set; }
        public string TagSample { get; set; }
        public bool IsOutsourcing { get; set; }
        public bool isDelete { get; set; }
        public string PacksRemark { get; set; }
        public Nullable<int> ApproverIndex { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateTerminal { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateTerminal { get; set; }
        public int PacksStatus { get; set; }
    
        public virtual Purchase_Contract Purchase_Contract { get; set; }
        public virtual ICollection<Purchase_OutContractsPacks> Purchase_OutContractsPacks { get; set; }
        public virtual ICollection<Purchase_PackProducts> Purchase_PackProducts { get; set; }
    }
}
