//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_PackProducts
    {
        public int ID { get; set; }
        public int PacksID { get; set; }
        public int OrderProductID { get; set; }
        public bool isDelete { get; set; }
        public int PPPUPCID { get; set; }
        public int ProductTagsNumber { get; set; }
        public int InnerTagsNumber { get; set; }
        public int OutTagsNumber { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Purchase_PackProductsUPC Purchase_PackProductsUPC { get; set; }
        public virtual Purchase_Packs Purchase_Packs { get; set; }
    }
}
