//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_District
    {
        public int DIID { get; set; }
        public Nullable<int> COID { get; set; }
        public Nullable<int> ARID { get; set; }
        public Nullable<int> CIID { get; set; }
        public string AreaName { get; set; }
        public string Abbreviation { get; set; }
        public string AbbreviationA { get; set; }
    }
}
