//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_SendSamples
    {
        public Sale_SendSamples()
        {
            this.Sale_ProductsSample = new HashSet<Sale_ProductsSample>();
            this.Sale_SendSampleHis = new HashSet<Sale_SendSampleHis>();
        }
    
        public int SSID { get; set; }
        public Nullable<int> QTID { get; set; }
        public Nullable<int> PHID { get; set; }
        public int FactureID { get; set; }
        public int CustomerID { get; set; }
        public int CreateWay { get; set; }
        public string FacManufactureID { get; set; }
        public int SampleStatus { get; set; }
        public Nullable<int> AcceptedStatus { get; set; }
        public int SampleModNum { get; set; }
        public Nullable<int> PaymentWay { get; set; }
        public Nullable<int> AcceptedInfo { get; set; }
        public string ExpressToLTD { get; set; }
        public string ToAcount { get; set; }
        public string ExpressFromLTD { get; set; }
        public Nullable<int> SendPieceNum { get; set; }
        public string PhaseExplan_1 { get; set; }
        public string PhaseExplan_2 { get; set; }
        public string ExpressID { get; set; }
        public Nullable<decimal> ExpressCost { get; set; }
        public string ValueA { get; set; }
        public string ValueB { get; set; }
        public string ValueC { get; set; }
        public string ValueD { get; set; }
        public string NoteA { get; set; }
        public string NoteB { get; set; }
        public string NoteC { get; set; }
        public Nullable<System.DateTime> DateTimeA { get; set; }
        public Nullable<System.DateTime> DateTimeB { get; set; }
        public Nullable<System.DateTime> DateTimeC { get; set; }
        public Nullable<System.DateTime> DateTimeD { get; set; }
        public Nullable<System.DateTime> DateTimeE { get; set; }
        public Nullable<System.DateTime> DateTimeF { get; set; }
        public Nullable<System.DateTime> DateTimeG { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public string CreateTerminal { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateTerminal { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> ActualFinishDate { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Orders_AcceptInformation Orders_AcceptInformation { get; set; }
        public virtual Orders_Customers Orders_Customers { get; set; }
        public virtual Quot_Quot Quot_Quot { get; set; }
        public virtual ICollection<Sale_ProductsSample> Sale_ProductsSample { get; set; }
        public virtual ICollection<Sale_SendSampleHis> Sale_SendSampleHis { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual Order Order { get; set; }
    }
}
