//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_SendSampleHis
    {
        public int SSHID { get; set; }
        public int SSID { get; set; }
        public string PhaseExplan { get; set; }
        public int SampleStatus { get; set; }
        public Nullable<System.DateTime> DateTimeA { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int AuditUserID { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Sale_SendSamples Sale_SendSamples { get; set; }
    }
}
