//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendSample
    {
        public int SSID { get; set; }
        public Nullable<int> QTID { get; set; }
        public Nullable<int> PHID { get; set; }
        public Nullable<decimal> CreateWay { get; set; }
        public Nullable<decimal> FacManufactureID { get; set; }
        public Nullable<decimal> FactureID { get; set; }
        public Nullable<decimal> CustomerID { get; set; }
        public Nullable<decimal> SampleStatus { get; set; }
        public Nullable<decimal> AcceptedStatus { get; set; }
        public Nullable<decimal> SampleModNum { get; set; }
        public Nullable<decimal> PaymentWay { get; set; }
        public Nullable<decimal> AcceptedInfo { get; set; }
        public string ExpressToLTD { get; set; }
        public string ToAcount { get; set; }
        public string ExpressFromLTD { get; set; }
        public Nullable<decimal> SendPieceNum { get; set; }
        public string PhaseExplan_1 { get; set; }
        public string PhaseExplan_2 { get; set; }
        public string ValueA { get; set; }
        public string ValueB { get; set; }
        public string ValueC { get; set; }
        public string NoteA { get; set; }
        public string NoteB { get; set; }
        public string NoteC { get; set; }
        public string ExpressID { get; set; }
        public Nullable<decimal> ExpressCost { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> DateTimeA { get; set; }
        public Nullable<System.DateTime> DateTimeB { get; set; }
        public Nullable<System.DateTime> DateTimeC { get; set; }
        public Nullable<System.DateTime> DateTimeD { get; set; }
        public Nullable<System.DateTime> DateTimeE { get; set; }
        public Nullable<System.DateTime> DateTimeF { get; set; }
        public Nullable<System.DateTime> DateTimeG { get; set; }
        public string ValueD { get; set; }
    }
}
