//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment_Agencies
    {
        public Shipment_Agencies()
        {
            this.Delivery_ShipmentOrder = new HashSet<Delivery_ShipmentOrder>();
            this.Shipment_AgentFees = new HashSet<Shipment_AgentFees>();
        }
    
        public int ShippingAgencyID { get; set; }
        public string ShippingAgencyName { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public bool IsDeleted { get; set; }
        public string AgencyAddress { get; set; }
        public string WarehouseAddress { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<Delivery_ShipmentOrder> Delivery_ShipmentOrder { get; set; }
        public virtual ICollection<Shipment_AgentFees> Shipment_AgentFees { get; set; }
    }
}
