//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment_AgentFees
    {
        public int ID { get; set; }
        public int ShippingAgencyID { get; set; }
        public string Currency { get; set; }
        public decimal FeeDocument { get; set; }
        public decimal FeeDockOperation { get; set; }
        public decimal FeeYangShanPicking { get; set; }
        public decimal FeeFacilityManagement { get; set; }
        public decimal FeePortSecurity { get; set; }
        public decimal FeeImporterSecurityClassify { get; set; }
        public decimal FeeWarehousing { get; set; }
        public decimal FeePicking { get; set; }
        public decimal FeeCustomDeclaration { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public bool IsValid { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Shipment_Agencies Shipment_Agencies { get; set; }
    }
}
