//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.Classifies = new HashSet<Classify>();
            this.Delivery_Encasements = new HashSet<Delivery_Encasements>();
            this.Delivery_EncasementsHis = new HashSet<Delivery_EncasementsHis>();
            this.Delivery_ShipmentNotificationHistory = new HashSet<Delivery_ShipmentNotificationHistory>();
            this.Delivery_ShipmentOrder = new HashSet<Delivery_ShipmentOrder>();
            this.Delivery_ShipmentOrderHistory = new HashSet<Delivery_ShipmentOrderHistory>();
            this.Delivery_ShipmentRegisterFeesHistory = new HashSet<Delivery_ShipmentRegisterFeesHistory>();
            this.DocumentsIndexings = new HashSet<DocumentsIndexing>();
            this.DocumentsIndexingHistories = new HashSet<DocumentsIndexingHistory>();
            this.Factories = new HashSet<Factory>();
            this.Inspection_InspectionClearance = new HashSet<Inspection_InspectionClearance>();
            this.Inspection_InspectionClearanceHis = new HashSet<Inspection_InspectionClearanceHis>();
            this.Inspection_InspectionCustoms = new HashSet<Inspection_InspectionCustoms>();
            this.Inspection_InspectionCustomsHis = new HashSet<Inspection_InspectionCustomsHis>();
            this.Inspection_InspectionExchange = new HashSet<Inspection_InspectionExchange>();
            this.Inspection_InspectionExchangeHis = new HashSet<Inspection_InspectionExchangeHis>();
            this.Inspection_InspectionReceipt = new HashSet<Inspection_InspectionReceipt>();
            this.Inspection_InspectionReceiptHis = new HashSet<Inspection_InspectionReceiptHis>();
            this.Inspection_InspectionReceiptList = new HashSet<Inspection_InspectionReceiptList>();
            this.Orders = new HashSet<Order>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.Orders_Customers = new HashSet<Orders_Customers>();
            this.Plan_ProducePlan = new HashSet<Plan_ProducePlan>();
            this.Products = new HashSet<Product>();
            this.ProductFittings = new HashSet<ProductFitting>();
            this.Purchase_PacksHis = new HashSet<Purchase_PacksHis>();
            this.Purchase_Contract = new HashSet<Purchase_Contract>();
            this.Purchase_Contract1 = new HashSet<Purchase_Contract>();
            this.Purchase_OutContractHis = new HashSet<Purchase_OutContractHis>();
            this.Purchase_OutContracts = new HashSet<Purchase_OutContracts>();
            this.Purchase_ThirdPartyVerification = new HashSet<Purchase_ThirdPartyVerification>();
            this.Purchase_ThreeTimesQC = new HashSet<Purchase_ThreeTimesQC>();
            this.Quot_Quot = new HashSet<Quot_Quot>();
            this.Sale_SendSampleHis = new HashSet<Sale_SendSampleHis>();
            this.Sale_SendSamples = new HashSet<Sale_SendSamples>();
            this.Shipment_Agencies = new HashSet<Shipment_Agencies>();
            this.Shipment_AgentFees = new HashSet<Shipment_AgentFees>();
            this.SystemUsers1 = new HashSet<SystemUser>();
            this.ThirdParty_Inspection = new HashSet<ThirdParty_Inspection>();
            this.UserCustomerRelationships = new HashSet<UserCustomerRelationship>();
            this.UserCustomPageSettings = new HashSet<UserCustomPageSetting>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public string Portrait { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public bool IsSuperAdmin { get; set; }
        public int HierarchyID { get; set; }
        public string Email { get; set; }
        public short Status { get; set; }
        public short DataPermissionForProduct { get; set; }
        public short DataPermissionForQuote { get; set; }
        public short DataPermissionForSample { get; set; }
        public short DataPermissionForOrder { get; set; }
        public short DataPermissionForPurchase { get; set; }
        public short DataPermissionForPacks { get; set; }
        public short DataPermissionForOutsourcing { get; set; }
        public short DataPermissionForFactory { get; set; }
        public short DataPermissionForCustomer { get; set; }
        public short DataPermissionForShipmentAgency { get; set; }
        public short DataPermissionForDelivery { get; set; }
        public bool IsTestAccount { get; set; }
        public short DataPermissionForProducePlan { get; set; }
        public short ForInspectionReceipt { get; set; }
        public short ForInspectionCustoms { get; set; }
        public short ForInspectionClearance { get; set; }
        public short ForInspectionExchange { get; set; }
        public Nullable<short> ForThirdParty { get; set; }
        public Nullable<short> ForShippingMark { get; set; }
        public Nullable<short> ForDocumentsIndexing { get; set; }
        public string EmailSign { get; set; }
        public Nullable<short> ForFinance { get; set; }
        public string EmailPassword { get; set; }
    
        public virtual Hierarchy Hierarchy { get; set; }
        public virtual ICollection<Classify> Classifies { get; set; }
        public virtual ICollection<Delivery_Encasements> Delivery_Encasements { get; set; }
        public virtual ICollection<Delivery_EncasementsHis> Delivery_EncasementsHis { get; set; }
        public virtual ICollection<Delivery_ShipmentNotificationHistory> Delivery_ShipmentNotificationHistory { get; set; }
        public virtual ICollection<Delivery_ShipmentOrder> Delivery_ShipmentOrder { get; set; }
        public virtual ICollection<Delivery_ShipmentOrderHistory> Delivery_ShipmentOrderHistory { get; set; }
        public virtual ICollection<Delivery_ShipmentRegisterFeesHistory> Delivery_ShipmentRegisterFeesHistory { get; set; }
        public virtual ICollection<DocumentsIndexing> DocumentsIndexings { get; set; }
        public virtual ICollection<DocumentsIndexingHistory> DocumentsIndexingHistories { get; set; }
        public virtual ICollection<Factory> Factories { get; set; }
        public virtual ICollection<Inspection_InspectionClearance> Inspection_InspectionClearance { get; set; }
        public virtual ICollection<Inspection_InspectionClearanceHis> Inspection_InspectionClearanceHis { get; set; }
        public virtual ICollection<Inspection_InspectionCustoms> Inspection_InspectionCustoms { get; set; }
        public virtual ICollection<Inspection_InspectionCustomsHis> Inspection_InspectionCustomsHis { get; set; }
        public virtual ICollection<Inspection_InspectionExchange> Inspection_InspectionExchange { get; set; }
        public virtual ICollection<Inspection_InspectionExchangeHis> Inspection_InspectionExchangeHis { get; set; }
        public virtual ICollection<Inspection_InspectionReceipt> Inspection_InspectionReceipt { get; set; }
        public virtual ICollection<Inspection_InspectionReceiptHis> Inspection_InspectionReceiptHis { get; set; }
        public virtual ICollection<Inspection_InspectionReceiptList> Inspection_InspectionReceiptList { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<Orders_Customers> Orders_Customers { get; set; }
        public virtual ICollection<Plan_ProducePlan> Plan_ProducePlan { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductFitting> ProductFittings { get; set; }
        public virtual ICollection<Purchase_PacksHis> Purchase_PacksHis { get; set; }
        public virtual ICollection<Purchase_Contract> Purchase_Contract { get; set; }
        public virtual ICollection<Purchase_Contract> Purchase_Contract1 { get; set; }
        public virtual ICollection<Purchase_OutContractHis> Purchase_OutContractHis { get; set; }
        public virtual ICollection<Purchase_OutContracts> Purchase_OutContracts { get; set; }
        public virtual ICollection<Purchase_ThirdPartyVerification> Purchase_ThirdPartyVerification { get; set; }
        public virtual ICollection<Purchase_ThreeTimesQC> Purchase_ThreeTimesQC { get; set; }
        public virtual ICollection<Quot_Quot> Quot_Quot { get; set; }
        public virtual ICollection<Sale_SendSampleHis> Sale_SendSampleHis { get; set; }
        public virtual ICollection<Sale_SendSamples> Sale_SendSamples { get; set; }
        public virtual ICollection<Shipment_Agencies> Shipment_Agencies { get; set; }
        public virtual ICollection<Shipment_AgentFees> Shipment_AgentFees { get; set; }
        public virtual ICollection<SystemUser> SystemUsers1 { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual ICollection<ThirdParty_Inspection> ThirdParty_Inspection { get; set; }
        public virtual ICollection<UserCustomerRelationship> UserCustomerRelationships { get; set; }
        public virtual ICollection<UserCustomPageSetting> UserCustomPageSettings { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
