//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdParty_Inspection
    {
        public ThirdParty_Inspection()
        {
            this.ThirdParty_InspectionAuditNotice = new HashSet<ThirdParty_InspectionAuditNotice>();
            this.ThirdParty_InspectionDetectNotice = new HashSet<ThirdParty_InspectionDetectNotice>();
            this.ThirdParty_InspectionSamplingNotice = new HashSet<ThirdParty_InspectionSamplingNotice>();
        }
    
        public int ID { get; set; }
        public int PurchaseID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string InspectionContent { get; set; }
        public int StatusID { get; set; }
        public decimal InspectionAuditFee { get; set; }
        public decimal InspectionDetectFee { get; set; }
        public string InspectionName { get; set; }
        public string InspectionEmail { get; set; }
        public string InspectionPhoneNumber { get; set; }
        public string InspectionFax { get; set; }
        public System.DateTime DT_CREATEDATE { get; set; }
        public int ST_CREATEUSER { get; set; }
        public System.DateTime DT_MODIFYDATE { get; set; }
        public int ST_MODIFYUSER { get; set; }
        public string IPAddress { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<decimal> InspectionAuditFee_ForFactory { get; set; }
        public Nullable<decimal> InspectionDetectFee_ForFactory { get; set; }
        public Nullable<decimal> InspectionSamplingFee { get; set; }
        public Nullable<decimal> InspectionSamplingFee_ForFactory { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Purchase_Contract Purchase_Contract { get; set; }
        public virtual ICollection<ThirdParty_InspectionAuditNotice> ThirdParty_InspectionAuditNotice { get; set; }
        public virtual ICollection<ThirdParty_InspectionDetectNotice> ThirdParty_InspectionDetectNotice { get; set; }
        public virtual ICollection<ThirdParty_InspectionSamplingNotice> ThirdParty_InspectionSamplingNotice { get; set; }
    }
}
