//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowDetail
    {
        public int ID { get; set; }
        public int WorkflowID { get; set; }
        public short PassWorkflowType { get; set; }
        public string PassWorkflowConditions { get; set; }
        public short CurrentOwnerType { get; set; }
        public int CurrentOwner { get; set; }
        public short Index { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
