//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public Workflow()
        {
            this.WorkflowDetails = new HashSet<WorkflowDetail>();
        }
    
        public int WorkflowID { get; set; }
        public short WorkflowType { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public short WorkflowStatuts { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<WorkflowDetail> WorkflowDetails { get; set; }
    }
}
